spring:
  profiles:
    active: local

server:
  port: 8080
  error:
    whitelabel:
      enabled: true

---
spring:
  profiles: local   
   
server:
  tomcat:
    basedir: C:\javacafe\jc-elastic-demo\work
    accesslog:
      directory: C:\javacafe\jc-elastic-demo\etomcat
      pattern: '%h %l %u %t "%r" %s %b %D'
      enabled: true
      suffix: .log

logging:
  file: C:\javacafe\jc-elastic-demo\log4j\daily.log
  level:
    org.thymeleaf: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.quartz.core: INFO
    org.h2.server.web: INFO
    org.springframework.security: INFO
    com.opensymphony: INFO
            

---
spring:
  profiles: dev   
          
server:
  tomcat:
    basedir: /home/irteam/work
    accesslog:
      directory: /home/irteam/logs/etomcat
      pattern: '%h %l %u %t "%r" %s %b %D'
      enabled: true
      suffix: .log

logging:
  file: /home1/irteam/logs/log4j/daily.log
  config: classpath:logback-spring.xml
  
  
---
spring:
  profiles: real   
         
server:
  tomcat:
    basedir: /home/irteam/work
    accesslog:
      directory: /home/irteam/logs/etomcat
      pattern: '%h %l %u %t "%r" %s %b %D'
      enabled: true
      suffix: .log
      
logging:
  file: /home1/irteam/logs/log4j/daily.log
  config: classpath:logback-spring.xml      
      
  

  
  
  